-- Create a table for user profiles (extends auth.users)
create table public.user_profiles (
  id uuid references auth.users not null primary key,
  username text unique,
  avatar_url text,
  is_premium boolean default false,
  updated_at timestamp with time zone,
  
  constraint username_length check (char_length(username) >= 3)
);

-- Enable Row Level Security (RLS)
alter table public.user_profiles enable row level security;

-- Create policies for user_profiles
create policy "Public profiles are viewable by everyone."
  on public.user_profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on public.user_profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on public.user_profiles for update
  using ( auth.uid() = id );

-- Create a table for Saved Results
create table public.saved_results (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  content text not null,
  category text default 'General',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for saved_results
alter table public.saved_results enable row level security;

-- Create policies for saved_results
create policy "Users can create their own saved results."
  on public.saved_results for insert
  with check ( auth.uid() = user_id );

create policy "Users can view their own saved results."
  on public.saved_results for select
  using ( auth.uid() = user_id );

create policy "Users can delete their own saved results."
  on public.saved_results for delete
  using ( auth.uid() = user_id );

-- Create a table for User History
create table public.user_history (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  content text not null,
  category text default 'General',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for user_history
alter table public.user_history enable row level security;

-- Create policies for user_history
create policy "Users can create their own history."
  on public.user_history for insert
  with check ( auth.uid() = user_id );

create policy "Users can view their own history."
  on public.user_history for select
  using ( auth.uid() = user_id );

create policy "Users can delete their own history."
  on public.user_history for delete
  using ( auth.uid() = user_id );

-- Set up Realtime for these tables (Optional, but good for sync)
alter publication supabase_realtime add table public.saved_results;
alter publication supabase_realtime add table public.user_history;
