# Script para agregar el sistema de compartir a todas las categorías
# Ejecutar desde la carpeta raíz del proyecto

$categories = @("pickup", "roasts", "tiktok", "sarcastic", "pets", "phrases", "excuses", "bios", "crush", "gamers", "whatsapp")

$cssToAdd = @"
    .share-section { margin-top: 15px; padding: 15px; background: #f5f5f5; border-radius: 10px; border: 2px dashed #ddd; }
    .share-title { font-weight: bold; margin-bottom: 10px; color: #333; font-size: 1rem; }
    .main-share-btn { margin-left: 8px; padding: 0.3rem 0.8rem; font-size: 0.9rem; background: #10b981; color: white; border: none; border-radius: 20px; cursor: pointer; transition: all 0.2s; }
    .main-share-btn:hover { background: #059669; transform: scale(1.05); }
"@

$htmlToAdd = @"
    <div id="share-section" style="display: none;">
      <div class="share-section">
        <div class="share-title" id="share-title">📱 Share on Social Media</div>
        <div class="share-buttons">
          <button class="share-btn twitter" onclick="shareOnTwitter()">🐦 Twitter</button>
          <button class="share-btn instagram" onclick="shareOnInstagram()">📸 Instagram</button>
          <button class="share-btn tiktok" onclick="shareOnTikTok()">🎵 TikTok</button>
          <button class="share-btn whatsapp" onclick="shareOnWhatsApp()">💬 WhatsApp</button>
          <button class="share-btn telegram" onclick="shareOnTelegram()">✈️ Telegram</button>
        </div>
      </div>
    </div>
"@

$jsToggleFunction = @"
    function toggleShareSection() {
      const shareSection = document.getElementById("share-section");
      const isVisible = shareSection.style.display !== "none";
      shareSection.style.display = isVisible ? "none" : "block";
    }
"@

$jsSharingFunctions = @"
    function shareOnTwitter() {
      const content = document.getElementById("output").textContent.split(" Copy")[0];
      const text = encodeURIComponent("Check out this from Namerly: " + content + " #Namerly #Creative");
      window.open("https://twitter.com/intent/tweet?text=" + text, "_blank");
    }

    function shareOnInstagram() {
      const content = document.getElementById("output").textContent.split(" Copy")[0];
      navigator.clipboard.writeText(content + " - Generated by Namerly");
      alert("Content copied! Open Instagram and paste it in your story or post.");
    }

    function shareOnTikTok() {
      const content = document.getElementById("output").textContent.split(" Copy")[0];
      navigator.clipboard.writeText(content + " #Namerly #Creative");
      alert("Content copied! Open TikTok and paste it in your video description.");
    }

    function shareOnWhatsApp() {
      const content = document.getElementById("output").textContent.split(" Copy")[0];
      const text = encodeURIComponent("Check this out: " + content + " 🔥");
      window.open("https://wa.me/?text=" + text, "_blank");
    }

    function shareOnTelegram() {
      const content = document.getElementById("output").textContent.split(" Copy")[0];
      const text = encodeURIComponent("Check this out: " + content + " 🔥");
      window.open("https://t.me/share/url?text=" + text, "_blank");
    }
"@

Write-Host "🚀 Iniciando actualización del sistema de compartir..."

foreach ($category in $categories) {
    $filePath = ".\$category\index.html"
    
    if (Test-Path $filePath) {
        Write-Host "📁 Procesando: $category"
        
        # Leer el archivo
        $content = Get-Content $filePath -Raw -Encoding UTF8
        
        # Agregar CSS si no existe
        if ($content -notmatch "share-section") {
            $content = $content -replace "(\s+)\.copy-btn", "$1$cssToAdd`r`n$1.copy-btn"
        }
        
        # Agregar HTML del share-section si no existe
        if ($content -notmatch "share-section") {
            $content = $content -replace "(</main>)", "$htmlToAdd`r`n  $1"
        }
        
        # Agregar funciones JavaScript si no existen
        if ($content -notmatch "toggleShareSection") {
            $content = $content -replace "(function copyToClipboard)", "$jsToggleFunction`r`n`r`n$jsSharingFunctions`r`n`r`n    $1"
        }
        
        # Agregar traduciones para share/shareTitle si no existen
        if ($content -notmatch '"share":') {
            $content = $content -replace '("copy": "[^"]+",)', '$1`r`n        "share": "Share",`r`n        "shareTitle": "📱 Share on Social Media",'
            $content = $content -replace '("copy": "[^"]+",)', '$1`r`n        "share": "Compartir",`r`n        "shareTitle": "📱 Compartir en Redes Sociales",'
        }
        
        # Actualizar la función de generación para incluir el botón de compartir
        if ($content -match 'document\.getElementById\("output"\)\.innerHTML = `([^`]+)` <button class="copy-btn"') {
            $content = $content -replace 'document\.getElementById\("output"\)\.innerHTML = `([^`]+)` <button class="copy-btn" onclick="copyToClipboard\([^)]+\)">([^<]+)</button>`', 'document.getElementById("output").innerHTML = `$1 <button class="copy-btn" onclick="copyToClipboard($1)">${t.copy}</button> <button class="main-share-btn" onclick="toggleShareSection()">${t.share}</button>`;'
        }
        
        # Escribir el archivo actualizado
        $content | Set-Content $filePath -Encoding UTF8
        
        Write-Host "✅ Completado: $category"
    } else {
        Write-Host "❌ No encontrado: $category"
    }
}

Write-Host "🎉 ¡Actualización completada! Todas las categorías ahora tienen el sistema de compartir."
